### ISSUE TITLE
PlaneMode.netkan ksp_version_max 1.12.2, but 1.12.3 is current stable release

### ISSUE THREAD

**Issue by RussellAult** [Apokee/PlaneMode#84]
Was there a breaking change in 1.12.3 that would affect PlaneMode?

If not (and given that there haven't been any non-`.netkan` changes to the codebase in quite a while), perhaps it might be safe enough to simply remove the `ksp_version_max` for the current version (or set it to `'any'`)?

Thanks!

**Comment by dbent** [comment]
No, but I like to test against a version myself before asserting compatibility with it. I just hadn't realized that 1.12.3 had been released. I've tested and updated the netkan.
